version: 2

builds:
  - dir: .

brews:
  - name: pman
    homepage: "https://github.com/bishalr0y/pman"
    description: "Terminal process manager"
    license: "MIT"

    repository:
      owner: bishalr0y
      name: homebrew-bishalr0y

    directory: Formula
